name: nexus_app_min_test
description: Minimal build to validate iOS simulator setup.
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^13.2.5
  equatable: ^2.0.5
  intl: ^0.20.2

  

  #firebase_core: ^2.32.0
  #cloud_firestore: ^4.17.5



flutter:
  uses-material-design: true

  # Keep your assets/fonts so theme works
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
