name: nexus_app_min_test
description: Minimal build to validate iOS simulator setup.
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  just_audio: ^0.9.38
  google_mlkit_face_detection: ^0.13.1
  country_picker: ^2.0.27
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^13.2.5
  equatable: ^2.0.5
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_messaging: ^16.1.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  firebase_storage: ^13.0.5
  google_mlkit_commons: ^0.11.0
  confetti: ^0.8.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1

  

  #firebase_core: ^2.32.0
  #cloud_firestore: ^4.17.5



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/churches_v1.json
    - assets/data/nexus1_onboarding_lists.v1.json

  # Keep your assets/fonts so theme works
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
